// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.service;

import br.ufpb.dcx.model.AlternativaDeQuestaoDeMultiplaEscolha;
import br.ufpb.dcx.service.AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl_Roo_Service {
    
    declare @type: AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl: @Service;
    
    declare @type: AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl: @Transactional;
    
    public long AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl.countAllAlternativaDeQuestaoDeMultiplaEscolhas() {
        return AlternativaDeQuestaoDeMultiplaEscolha.countAlternativaDeQuestaoDeMultiplaEscolhas();
    }
    
    public void AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl.deleteAlternativaDeQuestaoDeMultiplaEscolha(AlternativaDeQuestaoDeMultiplaEscolha alternativaDeQuestaoDeMultiplaEscolha) {
        alternativaDeQuestaoDeMultiplaEscolha.remove();
    }
    
    public AlternativaDeQuestaoDeMultiplaEscolha AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl.findAlternativaDeQuestaoDeMultiplaEscolha(Long id) {
        return AlternativaDeQuestaoDeMultiplaEscolha.findAlternativaDeQuestaoDeMultiplaEscolha(id);
    }
    
    public List<AlternativaDeQuestaoDeMultiplaEscolha> AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl.findAllAlternativaDeQuestaoDeMultiplaEscolhas() {
        return AlternativaDeQuestaoDeMultiplaEscolha.findAllAlternativaDeQuestaoDeMultiplaEscolhas();
    }
    
    public List<AlternativaDeQuestaoDeMultiplaEscolha> AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl.findAlternativaDeQuestaoDeMultiplaEscolhaEntries(int firstResult, int maxResults) {
        return AlternativaDeQuestaoDeMultiplaEscolha.findAlternativaDeQuestaoDeMultiplaEscolhaEntries(firstResult, maxResults);
    }
    
    public void AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl.saveAlternativaDeQuestaoDeMultiplaEscolha(AlternativaDeQuestaoDeMultiplaEscolha alternativaDeQuestaoDeMultiplaEscolha) {
        alternativaDeQuestaoDeMultiplaEscolha.persist();
    }
    
    public AlternativaDeQuestaoDeMultiplaEscolha AlternativaDeQuestaoDeMultiplaEscolhaServiceImpl.updateAlternativaDeQuestaoDeMultiplaEscolha(AlternativaDeQuestaoDeMultiplaEscolha alternativaDeQuestaoDeMultiplaEscolha) {
        return alternativaDeQuestaoDeMultiplaEscolha.merge();
    }
    
}
