// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.service;

import br.ufpb.dcx.model.AlternativaDeQuestaoDeMultiplaEscolha;
import br.ufpb.dcx.service.AlternativaDeQuestaoDeMultiplaEscolhaService;
import java.util.List;

privileged aspect AlternativaDeQuestaoDeMultiplaEscolhaService_Roo_Service {
    
    public abstract long AlternativaDeQuestaoDeMultiplaEscolhaService.countAllAlternativaDeQuestaoDeMultiplaEscolhas();    
    public abstract void AlternativaDeQuestaoDeMultiplaEscolhaService.deleteAlternativaDeQuestaoDeMultiplaEscolha(AlternativaDeQuestaoDeMultiplaEscolha alternativaDeQuestaoDeMultiplaEscolha);    
    public abstract AlternativaDeQuestaoDeMultiplaEscolha AlternativaDeQuestaoDeMultiplaEscolhaService.findAlternativaDeQuestaoDeMultiplaEscolha(Long id);    
    public abstract List<AlternativaDeQuestaoDeMultiplaEscolha> AlternativaDeQuestaoDeMultiplaEscolhaService.findAllAlternativaDeQuestaoDeMultiplaEscolhas();    
    public abstract List<AlternativaDeQuestaoDeMultiplaEscolha> AlternativaDeQuestaoDeMultiplaEscolhaService.findAlternativaDeQuestaoDeMultiplaEscolhaEntries(int firstResult, int maxResults);    
    public abstract void AlternativaDeQuestaoDeMultiplaEscolhaService.saveAlternativaDeQuestaoDeMultiplaEscolha(AlternativaDeQuestaoDeMultiplaEscolha alternativaDeQuestaoDeMultiplaEscolha);    
    public abstract AlternativaDeQuestaoDeMultiplaEscolha AlternativaDeQuestaoDeMultiplaEscolhaService.updateAlternativaDeQuestaoDeMultiplaEscolha(AlternativaDeQuestaoDeMultiplaEscolha alternativaDeQuestaoDeMultiplaEscolha);    
}
