// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.service;

import br.ufpb.dcx.model.RespostaDeQuestaoDissertativa;
import br.ufpb.dcx.service.RespostaDeQuestaoDissertativaServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RespostaDeQuestaoDissertativaServiceImpl_Roo_Service {
    
    declare @type: RespostaDeQuestaoDissertativaServiceImpl: @Service;
    
    declare @type: RespostaDeQuestaoDissertativaServiceImpl: @Transactional;
    
    public long RespostaDeQuestaoDissertativaServiceImpl.countAllRespostaDeQuestaoDissertativas() {
        return RespostaDeQuestaoDissertativa.countRespostaDeQuestaoDissertativas();
    }
    
    public void RespostaDeQuestaoDissertativaServiceImpl.deleteRespostaDeQuestaoDissertativa(RespostaDeQuestaoDissertativa respostaDeQuestaoDissertativa) {
        respostaDeQuestaoDissertativa.remove();
    }
    
    public RespostaDeQuestaoDissertativa RespostaDeQuestaoDissertativaServiceImpl.findRespostaDeQuestaoDissertativa(Long id) {
        return RespostaDeQuestaoDissertativa.findRespostaDeQuestaoDissertativa(id);
    }
    
    public List<RespostaDeQuestaoDissertativa> RespostaDeQuestaoDissertativaServiceImpl.findAllRespostaDeQuestaoDissertativas() {
        return RespostaDeQuestaoDissertativa.findAllRespostaDeQuestaoDissertativas();
    }
    
    public List<RespostaDeQuestaoDissertativa> RespostaDeQuestaoDissertativaServiceImpl.findRespostaDeQuestaoDissertativaEntries(int firstResult, int maxResults) {
        return RespostaDeQuestaoDissertativa.findRespostaDeQuestaoDissertativaEntries(firstResult, maxResults);
    }
    
    public void RespostaDeQuestaoDissertativaServiceImpl.saveRespostaDeQuestaoDissertativa(RespostaDeQuestaoDissertativa respostaDeQuestaoDissertativa) {
        respostaDeQuestaoDissertativa.persist();
    }
    
    public RespostaDeQuestaoDissertativa RespostaDeQuestaoDissertativaServiceImpl.updateRespostaDeQuestaoDissertativa(RespostaDeQuestaoDissertativa respostaDeQuestaoDissertativa) {
        return respostaDeQuestaoDissertativa.merge();
    }
    
}
