// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.service;

import br.ufpb.dcx.model.RespostaDeQuestaoDissertativa;
import br.ufpb.dcx.service.RespostaDeQuestaoDissertativaService;
import java.util.List;

privileged aspect RespostaDeQuestaoDissertativaService_Roo_Service {
    
    public abstract long RespostaDeQuestaoDissertativaService.countAllRespostaDeQuestaoDissertativas();    
    public abstract void RespostaDeQuestaoDissertativaService.deleteRespostaDeQuestaoDissertativa(RespostaDeQuestaoDissertativa respostaDeQuestaoDissertativa);    
    public abstract RespostaDeQuestaoDissertativa RespostaDeQuestaoDissertativaService.findRespostaDeQuestaoDissertativa(Long id);    
    public abstract List<RespostaDeQuestaoDissertativa> RespostaDeQuestaoDissertativaService.findAllRespostaDeQuestaoDissertativas();    
    public abstract List<RespostaDeQuestaoDissertativa> RespostaDeQuestaoDissertativaService.findRespostaDeQuestaoDissertativaEntries(int firstResult, int maxResults);    
    public abstract void RespostaDeQuestaoDissertativaService.saveRespostaDeQuestaoDissertativa(RespostaDeQuestaoDissertativa respostaDeQuestaoDissertativa);    
    public abstract RespostaDeQuestaoDissertativa RespostaDeQuestaoDissertativaService.updateRespostaDeQuestaoDissertativa(RespostaDeQuestaoDissertativa respostaDeQuestaoDissertativa);    
}
