// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.service;

import br.ufpb.dcx.model.RespostaDeQuestaoDeMultiplaEscolha;
import br.ufpb.dcx.service.RespostaDeQuestaoDeMultiplaEscolhaService;
import java.util.List;

privileged aspect RespostaDeQuestaoDeMultiplaEscolhaService_Roo_Service {
    
    public abstract long RespostaDeQuestaoDeMultiplaEscolhaService.countAllRespostaDeQuestaoDeMultiplaEscolhas();    
    public abstract void RespostaDeQuestaoDeMultiplaEscolhaService.deleteRespostaDeQuestaoDeMultiplaEscolha(RespostaDeQuestaoDeMultiplaEscolha respostaDeQuestaoDeMultiplaEscolha);    
    public abstract RespostaDeQuestaoDeMultiplaEscolha RespostaDeQuestaoDeMultiplaEscolhaService.findRespostaDeQuestaoDeMultiplaEscolha(Long id);    
    public abstract List<RespostaDeQuestaoDeMultiplaEscolha> RespostaDeQuestaoDeMultiplaEscolhaService.findAllRespostaDeQuestaoDeMultiplaEscolhas();    
    public abstract List<RespostaDeQuestaoDeMultiplaEscolha> RespostaDeQuestaoDeMultiplaEscolhaService.findRespostaDeQuestaoDeMultiplaEscolhaEntries(int firstResult, int maxResults);    
    public abstract void RespostaDeQuestaoDeMultiplaEscolhaService.saveRespostaDeQuestaoDeMultiplaEscolha(RespostaDeQuestaoDeMultiplaEscolha respostaDeQuestaoDeMultiplaEscolha);    
    public abstract RespostaDeQuestaoDeMultiplaEscolha RespostaDeQuestaoDeMultiplaEscolhaService.updateRespostaDeQuestaoDeMultiplaEscolha(RespostaDeQuestaoDeMultiplaEscolha respostaDeQuestaoDeMultiplaEscolha);    
}
