// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.service;

import br.ufpb.dcx.model.RespostaDeQuestaoDeUmExercicio;
import br.ufpb.dcx.service.RespostaDeQuestaoDeUmExercicioService;
import java.util.List;

privileged aspect RespostaDeQuestaoDeUmExercicioService_Roo_Service {
    
    public abstract long RespostaDeQuestaoDeUmExercicioService.countAllRespostaDeQuestaoDeUmExercicios();    
    public abstract void RespostaDeQuestaoDeUmExercicioService.deleteRespostaDeQuestaoDeUmExercicio(RespostaDeQuestaoDeUmExercicio respostaDeQuestaoDeUmExercicio);    
    public abstract RespostaDeQuestaoDeUmExercicio RespostaDeQuestaoDeUmExercicioService.findRespostaDeQuestaoDeUmExercicio(Long id);    
    public abstract List<RespostaDeQuestaoDeUmExercicio> RespostaDeQuestaoDeUmExercicioService.findAllRespostaDeQuestaoDeUmExercicios();    
    public abstract List<RespostaDeQuestaoDeUmExercicio> RespostaDeQuestaoDeUmExercicioService.findRespostaDeQuestaoDeUmExercicioEntries(int firstResult, int maxResults);    
    public abstract void RespostaDeQuestaoDeUmExercicioService.saveRespostaDeQuestaoDeUmExercicio(RespostaDeQuestaoDeUmExercicio respostaDeQuestaoDeUmExercicio);    
    public abstract RespostaDeQuestaoDeUmExercicio RespostaDeQuestaoDeUmExercicioService.updateRespostaDeQuestaoDeUmExercicio(RespostaDeQuestaoDeUmExercicio respostaDeQuestaoDeUmExercicio);    
}
