// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.jsf;

import br.ufpb.dcx.jsf.LoginBean;
import java.io.Serializable;

privileged aspect LoginBean_Roo_Serializable {
    
    declare parents: LoginBean implements Serializable;
    
}
