// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.jsf;

import br.ufpb.dcx.jsf.QuestaoDeMultiplaEscolhaBean;
import java.io.Serializable;

privileged aspect QuestaoDeMultiplaEscolhaBean_Roo_Serializable {
    
    declare parents: QuestaoDeMultiplaEscolhaBean implements Serializable;
    
}
