// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.model;

import br.ufpb.dcx.model.AlternativaDeQuestaoDeMultiplaEscolha;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AlternativaDeQuestaoDeMultiplaEscolha_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager AlternativaDeQuestaoDeMultiplaEscolha.entityManager;
    
    public static final List<String> AlternativaDeQuestaoDeMultiplaEscolha.fieldNames4OrderClauseFilter = java.util.Arrays.asList("serialVersionUID", "descricao", "alternativaCorreta");
    
    public static final EntityManager AlternativaDeQuestaoDeMultiplaEscolha.entityManager() {
        EntityManager em = new AlternativaDeQuestaoDeMultiplaEscolha().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long AlternativaDeQuestaoDeMultiplaEscolha.countAlternativaDeQuestaoDeMultiplaEscolhas() {
        return entityManager().createQuery("SELECT COUNT(o) FROM AlternativaDeQuestaoDeMultiplaEscolha o", Long.class).getSingleResult();
    }
    
    public static List<AlternativaDeQuestaoDeMultiplaEscolha> AlternativaDeQuestaoDeMultiplaEscolha.findAllAlternativaDeQuestaoDeMultiplaEscolhas() {
        return entityManager().createQuery("SELECT o FROM AlternativaDeQuestaoDeMultiplaEscolha o", AlternativaDeQuestaoDeMultiplaEscolha.class).getResultList();
    }
    
    public static List<AlternativaDeQuestaoDeMultiplaEscolha> AlternativaDeQuestaoDeMultiplaEscolha.findAllAlternativaDeQuestaoDeMultiplaEscolhas(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM AlternativaDeQuestaoDeMultiplaEscolha o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, AlternativaDeQuestaoDeMultiplaEscolha.class).getResultList();
    }
    
    public static AlternativaDeQuestaoDeMultiplaEscolha AlternativaDeQuestaoDeMultiplaEscolha.findAlternativaDeQuestaoDeMultiplaEscolha(Long id) {
        if (id == null) return null;
        return entityManager().find(AlternativaDeQuestaoDeMultiplaEscolha.class, id);
    }
    
    public static List<AlternativaDeQuestaoDeMultiplaEscolha> AlternativaDeQuestaoDeMultiplaEscolha.findAlternativaDeQuestaoDeMultiplaEscolhaEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM AlternativaDeQuestaoDeMultiplaEscolha o", AlternativaDeQuestaoDeMultiplaEscolha.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<AlternativaDeQuestaoDeMultiplaEscolha> AlternativaDeQuestaoDeMultiplaEscolha.findAlternativaDeQuestaoDeMultiplaEscolhaEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM AlternativaDeQuestaoDeMultiplaEscolha o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, AlternativaDeQuestaoDeMultiplaEscolha.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void AlternativaDeQuestaoDeMultiplaEscolha.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void AlternativaDeQuestaoDeMultiplaEscolha.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            AlternativaDeQuestaoDeMultiplaEscolha attached = AlternativaDeQuestaoDeMultiplaEscolha.findAlternativaDeQuestaoDeMultiplaEscolha(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void AlternativaDeQuestaoDeMultiplaEscolha.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void AlternativaDeQuestaoDeMultiplaEscolha.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public AlternativaDeQuestaoDeMultiplaEscolha AlternativaDeQuestaoDeMultiplaEscolha.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        AlternativaDeQuestaoDeMultiplaEscolha merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
