// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.model;

import br.ufpb.dcx.model.QuestaoDeMultiplaEscolha;
import javax.persistence.Entity;

privileged aspect QuestaoDeMultiplaEscolha_Roo_Jpa_Entity {
    
    declare @type: QuestaoDeMultiplaEscolha: @Entity;
    
}
