// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dcx.model;

import br.ufpb.dcx.model.RespostaDeQuestaoDissertativa;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RespostaDeQuestaoDissertativa_Roo_Configurable {
    
    declare @type: RespostaDeQuestaoDissertativa: @Configurable;
    
}
